name: Deploy ASP.NET Core MVC App to Azure App Service

on:
  push:
    branches: ["main"]

env:
  AZURE_WEBAPP_NAME: 'MyMvcApp-123e4567-e89b-12d3-a456-426614174000' # Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: '.' # Path to your web app project
  DOTNET_VERSION: '6.0.x' # .NET version to use
  RESOURCE_GROUP: 'GitHub-Copilot-Challenges' # Azure Resource Group

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Setup .NET ${{ env.DOTNET_VERSION }}'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Build and Publish'
      run: |
        dotnet publish -c Release -o output

    - name: 'Deploy ARM Template'
      run: |
        az deployment group create \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --template-file deploy.json \
          --parameters @deploy.parameters.json

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './output'

    - name: 'dotnet publish'
      run: |
        dotnet publish -c Release -o D:\a\MyMvcApp-Contact-Database-Application\output

    - name: 'Upload artifact for deployment job'
      run: |
        echo "Uploading deployment artifacts"
        dir D:\a\MyMvcApp-Contact-Database-Application\output