name: Deploy ASP.NET Core MVC App to Azure App Service

on:
  push:
    branches: ["main"]

env:
  AZURE_WEBAPP_NAME: 'MyMvcApp' # Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: '.' # Path to your web app project
  DOTNET_VERSION: '6.0.x' # .NET version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4

    - name: 'Setup .NET ${{ env.DOTNET_VERSION }}'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Build and Publish'
      run: |
        dotnet publish -c Release -o output

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './output'